version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: podevim_api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - podevim_net

  mysql:
    image: mysql:8
    container_name: podevim_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE=apiproject
      MYSQL_ROOT_PASSWORD=161709
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - podevim_net

volumes:
  mysql_data:

networks:
  podevim_net:
    driver: bridge
